[global.databases]
site = { url = "postgres://jer@localhost/site" }

[development]
address = "0.0.0.0"
port = 8000

[staging]
address = "0.0.0.0"
port = 8443

[production]
tls = { certs = "/etc/letsencrypt/live/jer.cx/fullchain.pem", key = "/etc/letsencrypt/live/jer.cx/privkey.pem" }
address = "0.0.0.0"
port = 8443

