[global.databases]
site = { url = "postgres://jer@localhost/site" }

[development]
address = "0.0.0.0"
port = 8000

[staging]
address = "0.0.0.0"
port = 8443

[production]
address = "0.0.0.0"
port = 8443

